Repository kha-devspaces/kha-trainee, pull requests merged in 2023-11, with the labels that each got.

#5 (feature) add hello world
  Jeng/README.md
Labels: enhancement

#7 (Feature:att) add hello world
  Att/README.md
Labels: enhancement

#10 bas add memo
  Bas/README.md
Labels: invalid

#14 Att Add Memo
  Att/README.md
Labels: documentation

#17 Ci/juii/add me
  Juii/README.md
Labels: invalid

#13 dont add memo
  Dont/README.md
Labels: invalid

#16 jeng add memo
  Jeng/README.md
Labels: enhancement

#11 tle add memo
  Tle/README.md
Labels: invalid

#20 add memo
  Ohm/README.md
Labels: invalid

#23 feat: :sparkles: add test text
  README.md
Labels: enhancement

#24 feat: :sparkles: add test2
  README.md
Labels: enhancement

#25 Feature/bas/layout
  README.md
Labels: enhancement

#26 Hotfix/bas/update memo index
  Bas/README.md
  README.md
Labels: bug

#27 Hotfix/bas/update memo
  Bas/README.md
  README.md
Labels: bug
